### PR TITLE
Bound `traitlets<5.10` and add test for issue observed in newer versions

### PR DESCRIPTION
**Pull request by consideRatio**
I've obseved that Dict, List, Instance, and Command trait types no longer gets their help strings set with traitlets 5.10.0 but this wasn't an issue in traitlets 5.9.0. I've now tracked this down to work all the way up to https://github.com/ipython/traitlets/pull/818 was merged.

Introducing this causes tests to fail, but they should fail because we have an issue right now. This has been observed in:
- https://github.com/jupyterhub/kubespawner/issues/788
- https://github.com/dask/dask-gateway/issues/744

### CODE REVIEW

**Comment by manics** [comment]
Could we put an upper bound on traitlets in
https://github.com/jupyterhub/autodoc-traits/blob/5632a2a5af47f52612bf81813eae560d584519b5/pyproject.toml#L23
And remove it when there's a fix?

**Comment by consideRatio** [comment]
Great idea @manics, done!

**Comment by consideRatio** [comment]
@manics OK to go for a patch release with this?

**Comment by manics** [comment]
A release sounds good to me!

**Pull request merged**
