### PR TITLE
docs: add fixme note about unexpected inherited-members option

### PR DESCRIPTION
**Pull request by consideRatio**
I observed something that I found quite odd and worth looking into. I opted to not make an issue but a fixme note instead.

### CODE REVIEW

**Comment by minrk** [comment]
This seems like a perfect case for issue, rather than a fixme note. Can I ask what you see is beneficial of the comment rather than an Issue? An issue seems much more likely to be noticed and addressed, whereas a fixme will only ever come up when reading through the code, which in turn only tends to happen when that part of the code is doing something wrong. I would only typically add a fixme in a PR adding _other_ code that doesn't yet do everything I'd like it to.

On first glance, it does seem like our logic is exactly backwards here, and we likely haven't noticed because we usually want inherited traits and this makes them on by default.

If our logic _is_ right, my guess is that the goal is to get all traits, and inherited members means we get them already, whereas not inherited members means we only need to add them from this class. That's just a guess and it needs tests.

**Comment by consideRatio** [comment]
Okay sure! I used the source code as documentation and the source of truth for how things worked, so having it there felt good as it could otherwise confuse someone like myself pending a fix that felt like something we may never do.

Suggestion:

I open an issue, then update this comment to link to it to help clarify that the logic is weird currently.

**Comment by minrk** [comment]
Sure! I'd also move most of the info out of the comment to the issue, and leave the comment as something brief with a link, e.g.

```
fixme: this use of inherited_members may be backwards, see issue https://....
```

**Comment by minrk** [comment]
a clarifying comment saying what it _actually_ does is also good, regardless of the fixme! e.g. class_own_traits is only the class's own traits, while class_traits includes inherited members. We collect inherited traits only when sphinx does _not_ request inherited members. Fixme: Is this backwards?

**Pull request merged**
