### PR TITLE
Add changelog for 1.0.0

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
LGTM!  (I think we should also include #10 though :smile:)

**Comment by consideRatio** [comment]
This ended up unmerged and I've now:
- opened #14
- opened #15
- opened #16
- merged #10 

Is it okay if we close this, and then go for merges on the newly opened? I'll open up a changelog PR soonish to get a release out!

**Comment by consideRatio** [comment]
If i read the title "add changelog for 1.0.0", its a notable difference in my understanding on whats done compared to "call it 1.0", so i went for the title change - felt a bit stubborn doing that since you just recently changed the title Min.

Title updates of PRs is something i generally think can help anyone overview things effectively with relative low intrusion, but still an intrusion.

Did that feel okay with you @minrk?

**Comment by minrk** [comment]
@consideRatio yes, absolutely! I just removed the text about pre-commit since i removed those commits, too. Your title is better.

**Pull request merged**
